name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    name: ${{ matrix.configuration }} ${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - .NET Debug
          - .NET Release
          - Debug
          - Release
          - Debug Static
          - Release Static
          - Unicode Debug
          - Unicode Release
          - Unicode Debug Static
          - Unicode Release Static
        platform: [x64, Win32]
    steps:
    - uses: actions/checkout@main
    - uses: microsoft/setup-msbuild@main

    - name: Restore NuGet packages
      run: nuget restore source/BugTrap.sln

    - name: Build
      run: msbuild /m /p:Configuration="${{ matrix.configuration }}" /p:Platform="${{ matrix.platform }}" source/BugTrap.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: BugTrap ${{ matrix.configuration }} ${{ matrix.platform }} (github-${{ github.run_number }})
        path: |
            include/*
            bin/*.dll
            bin/*.lib
            bin/*.pdb
