name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    name: ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [.NET Debug, .NET Release, Debug, Release, Unicode Debug, Unicode Release]
        Platform: [x64, Win32]
    steps:
    - uses: actions/checkout@main
    - uses: microsoft/setup-msbuild@main

    - name: Restore NuGet packages
      run: nuget restore source/BugTrap.sln

    - name: Build
      run: msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" source/BugTrap.sln
